# This is a basic workflow to help you get started with Actions

name: sync from gitee

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: git version
        run: |
          git --version
          pwd
      
      - name: git coinfig
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
        
      # git pull from gitee
      - name: git pull gitee master
        run: |
          git remote add gitee ${{ secrets.GITEE_AVIGATORFLOW }}
          git config pull.rebase false
          git remote -v
          git pull gitee master --allow-unrelated-histories
      
      - name: git push origin main
        run: |
          git push
      
      
